### ISSUE TITLE
Vagrant setup to play with local machine while developing

### ISSUE THREAD

**Issue by PVince81** [owncloud-ansible/playground#1]
To be able to test ownCloud's ansible scripts, I've got a local Vagrant setup with "ansible_local".

Would it make sense to check these in as it could help other people to get more quickly setup for developing and testing ?

**Comment by xoxys** [comment]
@PVince81 Yes, would like to add it. PR welcome :)

**Comment by PVince81** [comment]
@xoxys PR here https://github.com/PVince81/owncloud-ansible-playground/pull/1

**Comment by xoxys** [comment]
@PVince81 Cool. Can we have the PR against the master branch of this repo instead of yours? ;)

**Comment by PVince81** [comment]
@xoxys done https://github.com/owncloud-ansible/playground/pull/3

**Comment by xoxys** [comment]
Thanks! Added some comments.

**Comment by xoxys** [comment]
Merged #3
