### ISSUE TITLE
Support fact cache for faster deployment and testing

### ISSUE THREAD

**Issue by PVince81** [owncloud-ansible/playground#2]
With https://github.com/owncloud-ansible/playground/issues/1 I've added the following config file locally ansible.cfg:
```
[defaults]
fact_caching = jsonfile
fact_caching_connection = /tmp/ansible-facts
fact_caching_timeout = 86400
```

I did see in the log that this is being used.

However after provisioning there are no mentions of Apache or PHP inside the cached JSON files.
And the only mention of ownCloud is for bits of config.php.

So the provisioning is still very slow. This is cumbersome when testing configurations settings as it takes a while to get results.

@xoxys

**Comment by PVince81** [comment]
Does it mean all our roles have to be designed to actually store their facts into the cache instead of always re-checking against the live instance ?

**Comment by enbrnz** [comment]
Not something we want to include in our roles, this could be done locally in the ansible installation configuration.
