### ISSUE TITLE
"mariadb : Ensure dependencies are installed" failed

### ISSUE THREAD

**Issue by ValentinKruegl** [owncloud-ansible/playground#22]
we are using ubuntu-minimal on:
ubuntu 22.04 
php reverted to 7.4. 
mariadb 10.6.12

TASK [mariadb : Ensure dependencies are installed] 

failed: [db1] (item=centos-release-scl) => {"ansible_loop_var": "item", "changed": false, "item": "centos-release-scl", "msg": "No package matching 'centos-release-scl' is available"}

 removing centos-release-scl from database.yml  seems to fix this issue

**Comment by enbrnz** [comment]
Which `database.yml` are you referring to, as this does not contain the string `centos-release-scl`:
https://github.com/owncloud-ansible/playground/blob/main/inventories/ubuntu-minimal/group_vars/database.yml

Again, unfortunately I was unaware that this customer is using 22.04, which is currently still untested.

**Comment by ValentinKruegl** [comment]
This issue can be closed, we thought ubuntu-minimal needed extra packages and added one through mariadb_packages_extra: , so a mistake on our side.
